services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80 # Public HTTP Port
      - ${HTTPS_PORT}:443 # Public HTTPS Port
      - ${ADMIN_PORT}:81 # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
volumes:
  data:
  letsencrypt:
