services:
  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME} #I do this so I can run multiple instances on the same server and not conflict with names
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    labels:
      - "com.centurylinklabs.watchtower.enable=false" #Do not update with watchtower

  wordpress_whatsnewandrew:
    depends_on:
      - db
    image: wordpress
    ports:
      - ${PORT}:80
    container_name: ${WP_CONTAINER_NAME} #I do this so I can run multiple instances on the same server and not conflict with names
    volumes:
      - ${PATH_TO_WPDATA}:/var/www/html 
      #- wp_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    labels:
      - "com.centurylinklabs.watchtower.enable=false" #Do not update with watchtower
volumes:
    db_data: {} 
    wp_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /var/www/html/${WP_CONTAINER_NAME}
